version: '3.9'


services:
  nginx:
    container_name: ${DOMAIN_NAME}-nginx
    image: nginx:${NGINX_VER}-${ALPINE_VER}
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/etc/nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./src:/var/www/html

#  php-fpm8.1:
#    container_name: $$(DOMAIN_NAME)-php-sc
#  mysql:
#    container_name: $$(DOMAIN_NAME)-mysql


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.1/24

